# Generated by Django 3.2.7 on 2021-09-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('publication_timestamp', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254, null=True)),
                ('maintainer_name', models.CharField(max_length=255)),
                ('maintainer_email', models.EmailField(max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'package',
            },
        ),
    ]
